// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SkillBridge_dotnet.Api.Data;

#nullable disable

namespace SkillBridge_dotnet.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251114212514_AddProfileCompetency")]
    partial class AddProfileCompetency
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_general_ci")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SkillBridge_dotnet.Api.Models.Competency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("RecommendedLevel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("competencies");
                });

            modelBuilder.Entity("SkillBridge_dotnet.Api.Models.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<int>("DurationHours")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.HasKey("Id");

                    b.ToTable("courses");
                });

            modelBuilder.Entity("SkillBridge_dotnet.Api.Models.Enrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("Progress")
                        .HasColumnType("double");

                    b.Property<double?>("Score")
                        .HasColumnType("double");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("UserId", "CourseId");

                    b.ToTable("enrollments");
                });

            modelBuilder.Entity("SkillBridge_dotnet.Api.Models.Joins.CourseCompetency", b =>
                {
                    b.Property<Guid>("CourseId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CompetencyId")
                        .HasColumnType("char(36)");

                    b.Property<int>("CoveragePercent")
                        .HasColumnType("int");

                    b.Property<int>("RequiredLevel")
                        .HasColumnType("int");

                    b.HasKey("CourseId", "CompetencyId");

                    b.HasIndex("CompetencyId");

                    b.ToTable("course_competencies");
                });

            modelBuilder.Entity("SkillBridge_dotnet.Api.Models.Joins.ProfileCompetency", b =>
                {
                    b.Property<Guid>("ProfileId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CompetencyId")
                        .HasColumnType("char(36)");

                    b.Property<string>("SelfAssessedLevel")
                        .HasColumnType("longtext");

                    b.Property<int?>("YearsExperience")
                        .HasColumnType("int");

                    b.HasKey("ProfileId", "CompetencyId");

                    b.HasIndex("CompetencyId");

                    b.ToTable("profile_competencies");
                });

            modelBuilder.Entity("SkillBridge_dotnet.Api.Models.Joins.VacancyCompetency", b =>
                {
                    b.Property<Guid>("VacancyId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CompetencyId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("RequiredLevel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("VacancyId", "CompetencyId");

                    b.HasIndex("CompetencyId");

                    b.ToTable("vacancy_competencies");
                });

            modelBuilder.Entity("SkillBridge_dotnet.Api.Models.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("profiles");
                });

            modelBuilder.Entity("SkillBridge_dotnet.Api.Models.Recommendation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CourseId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("VacancyId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("ProfileId");

                    b.HasIndex("VacancyId");

                    b.ToTable("recommendations");
                });

            modelBuilder.Entity("SkillBridge_dotnet.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("SkillBridge_dotnet.Api.Models.Vacancy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ClosesAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime>("PostedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("SalaryMax")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("SalaryMin")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.HasKey("Id");

                    b.ToTable("vacancies");
                });

            modelBuilder.Entity("SkillBridge_dotnet.Api.Models.Enrollment", b =>
                {
                    b.HasOne("SkillBridge_dotnet.Api.Models.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillBridge_dotnet.Api.Models.User", "User")
                        .WithMany("Enrollments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SkillBridge_dotnet.Api.Models.Joins.CourseCompetency", b =>
                {
                    b.HasOne("SkillBridge_dotnet.Api.Models.Competency", "Competency")
                        .WithMany("CourseCompetencies")
                        .HasForeignKey("CompetencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillBridge_dotnet.Api.Models.Course", "Course")
                        .WithMany("CourseCompetencies")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competency");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("SkillBridge_dotnet.Api.Models.Joins.ProfileCompetency", b =>
                {
                    b.HasOne("SkillBridge_dotnet.Api.Models.Competency", "Competency")
                        .WithMany("ProfileCompetencies")
                        .HasForeignKey("CompetencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillBridge_dotnet.Api.Models.Profile", "Profile")
                        .WithMany("ProfileCompetencies")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competency");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("SkillBridge_dotnet.Api.Models.Joins.VacancyCompetency", b =>
                {
                    b.HasOne("SkillBridge_dotnet.Api.Models.Competency", "Competency")
                        .WithMany("VacancyCompetencies")
                        .HasForeignKey("CompetencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillBridge_dotnet.Api.Models.Vacancy", "Vacancy")
                        .WithMany("VacancyCompetencies")
                        .HasForeignKey("VacancyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competency");

                    b.Navigation("Vacancy");
                });

            modelBuilder.Entity("SkillBridge_dotnet.Api.Models.Profile", b =>
                {
                    b.HasOne("SkillBridge_dotnet.Api.Models.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("SkillBridge_dotnet.Api.Models.Profile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("SkillBridge_dotnet.Api.Models.Recommendation", b =>
                {
                    b.HasOne("SkillBridge_dotnet.Api.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId");

                    b.HasOne("SkillBridge_dotnet.Api.Models.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillBridge_dotnet.Api.Models.Vacancy", "Vacancy")
                        .WithMany()
                        .HasForeignKey("VacancyId");

                    b.Navigation("Course");

                    b.Navigation("Profile");

                    b.Navigation("Vacancy");
                });

            modelBuilder.Entity("SkillBridge_dotnet.Api.Models.Competency", b =>
                {
                    b.Navigation("CourseCompetencies");

                    b.Navigation("ProfileCompetencies");

                    b.Navigation("VacancyCompetencies");
                });

            modelBuilder.Entity("SkillBridge_dotnet.Api.Models.Course", b =>
                {
                    b.Navigation("CourseCompetencies");

                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("SkillBridge_dotnet.Api.Models.Profile", b =>
                {
                    b.Navigation("ProfileCompetencies");
                });

            modelBuilder.Entity("SkillBridge_dotnet.Api.Models.User", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("Profile")
                        .IsRequired();
                });

            modelBuilder.Entity("SkillBridge_dotnet.Api.Models.Vacancy", b =>
                {
                    b.Navigation("VacancyCompetencies");
                });
#pragma warning restore 612, 618
        }
    }
}
